version: "3.9"

services:
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./derpibooru_public_dump_2023_05_29.pgdump:/derpibooru_public_dump_2023_05_29.pgdump
      - ./restore.sh:/docker-entrypoint-initdb.d/restore.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: derpibooru
      POSTGRES_DB: derpibooru

volumes:
  postgres_data: { }